"""add_is_active_to_parking_lot

Revision ID: 85e46796b4a7
Revises: bd1ba1512fb2
Create Date: 2025-07-26 11:58:25.648057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e46796b4a7'
down_revision = 'bd1ba1512fb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_lot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_lot', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
