"""Redesign ParkingHistory: add released_time, total_cost, spot_id, parking_time, status; remove action and timestamp

Revision ID: 9866d6bc4c2c
Revises: df95d802302e
Create Date: 2025-07-17 22:46:19.790663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9866d6bc4c2c'
down_revision = 'df95d802302e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spot_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parking_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('released_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key('fk_parking_history_spot_id', 'parking_spot', ['spot_id'], ['id'])
        batch_op.drop_column('action')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('action', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('total_cost')
        batch_op.drop_column('released_time')
        batch_op.drop_column('parking_time')
        batch_op.drop_column('spot_id')

    # ### end Alembic commands ###
