"""Add app_config table

Revision ID: bd1ba1512fb2
Revises: 9866d6bc4c2c
Create Date: 2025-07-22 00:53:54.429385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1ba1512fb2'
down_revision = '9866d6bc4c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('parking_history', schema=None) as batch_op:
        batch_op.alter_column('spot_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_history', schema=None) as batch_op:
        batch_op.alter_column('spot_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('app_config')
    # ### end Alembic commands ###
