"""Add address, pincode, price_per_hour, max_spots to ParkingLot

Revision ID: fb1dfb0ee1d2
Revises: a589da771626
Create Date: 2025-06-30 16:53:35.586873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1dfb0ee1d2'
down_revision = 'a589da771626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_lot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('pincode', sa.String(length=20), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('price_per_hour', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('max_spots', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_lot', schema=None) as batch_op:
        batch_op.drop_column('max_spots')
        batch_op.drop_column('price_per_hour')
        batch_op.drop_column('pincode')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
